[[mgr.prepend_keymap]]
on = [ "u", "a" ]
run = "plugin yamb save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = [ "u", "g" ]
run = "plugin yamb jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "f" ]
run = "plugin yamb jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "d" ]
run = "plugin yamb delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "D" ]
run = "plugin yamb delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "A" ]
run = "plugin yamb delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "u", "r" ]
run = "plugin yamb rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "R" ]
run = "plugin yamb rename_by_fzf"
desc = "Rename bookmark by fzf"

# tabs
[[mgr.prepend_keymap]]
on = [ "t", "1" ]
run = "tab_switch 0"
desc = "Switch to first tab"

[[mgr.prepend_keymap]]
on = [ "t", "2" ]
run = "tab_switch 1"
desc = "Switch to second tab"

[[mgr.prepend_keymap]]
on = [ "t", "3" ]
run = "tab_switch 2"
desc = "Switch to third tab"

[[mgr.prepend_keymap]]
on = [ "t", "4" ]
run = "tab_switch 3"
desc = "Switch to fourth tab"

[[mgr.prepend_keymap]]
on = [ "t", "5" ]
run = "tab_switch 4"
desc = "Switch to fifth tab"

[[mgr.prepend_keymap]]
on = [ "t", "6" ]
run = "tab_switch 5"
desc = "Switch to sixth tab"

[[mgr.prepend_keymap]]
on = [ "t", "7" ]
run = "tab_switch 6"
desc = "Switch to seventh tab"

[[mgr.prepend_keymap]]
on = [ "t", "8" ]
run = "tab_switch 7"
desc = "Switch to eighth tab"

[[mgr.prepend_keymap]]
on = [ "t", "9" ]
run = "tab_switch 8"
desc = "Switch to ninth tab"

# # relative-motions
# [[mgr.prepend_keymap]]
# on = [ "1" ]
# run = "plugin relative-motions 1"
# desc = "Move in relative steps"
#
# [[mgr.prepend_keymap]]
# on = [ "2" ]
# run = "plugin relative-motions 2"
# desc = "Move in relative steps"
#
# [[mgr.prepend_keymap]]
# on = [ "3" ]
# run = "plugin relative-motions 3"
# desc = "Move in relative steps"
#
# [[mgr.prepend_keymap]]
# on = [ "4" ]
# run = "plugin relative-motions 4"
# desc = "Move in relative steps"
#
# [[mgr.prepend_keymap]]
# on = [ "5" ]
# run = "plugin relative-motions 5"
# desc = "Move in relative steps"
#
# [[mgr.prepend_keymap]]
# on = [ "6" ]
# run = "plugin relative-motions 6"
# desc = "Move in relative steps"
#
# [[mgr.prepend_keymap]]
# on = [ "7" ]
# run = "plugin relative-motions 7"
# desc = "Move in relative steps"
#
# [[mgr.prepend_keymap]]
# on = [ "8" ]
# run = "plugin relative-motions 8"
# desc = "Move in relative steps"
#
# [[mgr.prepend_keymap]]
# on = [ "9" ]
# run = "plugin relative-motions 9"
# desc = "Move in relative steps"

# clipboard
# Copy selected/hovered files to the system clipboard
[[mgr.prepend_keymap]]
on  = "<C-y>"
run = "plugin system-clipboard"
desc = "Copy files to system clipboard"

# Paste files from the system clipboard into the current directory
[[mgr.prepend_keymap]]
on  = "<C-p>"
run = "shell 'cb paste'"
desc = "Paste files from system clipboard"
